version: '3.8'

services:
  mariadb:
    image: mariadb:11.2
    restart: always
    environment:
      MARIADB_DATABASE: 'db'
      MARIADB_USER: 'admin'
      MARIADB_PASSWORD: 'admin'
      MARIADB_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mariadb

volumes:
  data:
